version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepass
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../backend/.env
    depends_on:
      - db
    ports:
      - '4000:4000'
    volumes:
      - ../backend:/app          # Monta todo el código para desarrollo en caliente
      - /app/node_modules       # Mantiene los node_modules del contenedor
    command: npm run dev        # Arranca en modo desarrollo (nodemon/ts-node)

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:4000

volumes:
  db_data: