# infra/docker-compose.yml
version: '3.8'
services:
  db:
    build: ./database
    ports: ['5432:5432']
    volumes: ['db_data:/var/lib/postgresql/data']
  backend:
    build: ./backend
    env_file: ./backend/.env
    depends_on: ['db']
    ports: ['4000:4000']
  frontend:
    build: ./frontend
    ports: ['3000:3000']
volumes:
  db_data:
